namespace BunnyTail.MemberAccessor;

using Microsoft.CodeAnalysis;

// Diagnostic coverage for AccessorGenerator.
// The other tests in this project exercise generated code at run time, which by construction
// can only cover inputs the generator accepts. These cover the refusals.
public class DiagnosticTest
{
    //-----------------------------------------------------------------------
    // BTMA0001 : [TypedAccessor] target must be a generic type
    //-----------------------------------------------------------------------

    [Fact]
    public void Btma0001NonGenericTypedAccessorEmitsDiagnostic()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnostics(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [GenerateAccessor]
            public partial class Simple
            {
                public int Id { get; set; }
            }

            [TypedAccessor(typeof(Simple))]
            public static partial class Registration
            {
            }
            """);

        Assert.Contains(diagnostics, static x => x.Id == "BTMA0001");
    }

    //-----------------------------------------------------------------------
    // BTMA0003 : type has no accessible member
    //-----------------------------------------------------------------------

    [Fact]
    public void Btma0003NoAccessibleMemberEmitsDiagnostic()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnostics(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [GenerateAccessor]
            public partial class Empty
            {
            }
            """);

        Assert.Contains(diagnostics, static x => x.Id == "BTMA0003");
    }

    //-----------------------------------------------------------------------
    // BTMA0004 : [TypedAccessor] target lacks [GenerateAccessor]
    //-----------------------------------------------------------------------

    [Fact]
    public void Btma0004TargetWithoutGenerateAccessorEmitsDiagnostic()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnostics(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [TypedAccessor(typeof(Plain<int>))]
            public partial class Plain<T>
            {
                public T? Value { get; set; }
            }
            """);

        Assert.Contains(diagnostics, static x => x.Id == "BTMA0004");
    }

    //-----------------------------------------------------------------------
    // BTMA0007 : [GenerateAccessorFor] target is not supported
    //-----------------------------------------------------------------------

    [Fact]
    public void Btma0007UnsupportedExternalTargetEmitsDiagnostic()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnostics(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            public interface IContract
            {
                int Id { get; set; }
            }

            [GenerateAccessorFor(typeof(IContract))]
            public static partial class Witness
            {
            }
            """);

        Assert.Contains(diagnostics, static x => x.Id == "BTMA0007");
    }

    //-----------------------------------------------------------------------
    // BTMA0008 : target already generated by [GenerateAccessor]
    //-----------------------------------------------------------------------

    [Fact]
    public void Btma0008AlreadyGeneratedTargetEmitsDiagnostic()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnostics(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [GenerateAccessor]
            public partial class Data
            {
                public int Id { get; set; }
            }

            [GenerateAccessorFor(typeof(Data))]
            public static partial class Witness
            {
            }
            """);

        Assert.Contains(diagnostics, static x => x.Id == "BTMA0008");
    }

    //-----------------------------------------------------------------------
    // Valid input must stay clean
    //-----------------------------------------------------------------------

    [Fact]
    public void ValidAccessorEmitsNoDiagnostic()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnostics(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [GenerateAccessor]
            public partial class Data
            {
                public int Id { get; set; }

                public string Name { get; set; } = default!;
            }
            """);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public void ValidAccessorGeneratesSource()
    {
        var generated = GeneratorTestHelper.GetGeneratedSource(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [GenerateAccessor]
            public partial class Data
            {
                public int Id { get; set; }
            }
            """);

        Assert.Contains("Data", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void ValidAccessorProducesNoCompilationError()
    {
        var diagnostics = GeneratorTestHelper.GetDiagnosticsAll(
            """
            using BunnyTail.MemberAccessor;

            namespace Test;

            [GenerateAccessor]
            public partial class Data
            {
                public int Id { get; set; }
            }
            """);

        Assert.DoesNotContain(diagnostics, static x => x.Severity == DiagnosticSeverity.Error);
    }
}
